version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     networks: 
        internal:
          ipv4_address: 192.168.1.2
     environment:
       MYSQL_ROOT_PASSWORD: rootwordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress1:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wordpress_files:/var/www/html/wp-content/uploads
     networks: 
        internal:
          ipv4_address: 192.168.1.3
     ports:
       - "8080:80"
     environment:
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

   wordpress2:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wordpress_files:/var/www/html/wp-content/uploads
     networks: 
        internal:
          ipv4_address: 192.168.1.4
     ports:
       - "8081:80"
     environment:
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data:
    wordpress_files:

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/16
